### ISSUE TITLE
Kontrolle Aufgabe 03

### ISSUE THREAD

**Issue by MelvinBusch** [Gosselbe/EIA2#1]
1. Aufgaben im Steckbrief bitte untereinander verlinken.
2. AD's könnten ausführlicher sein.
3. In den AD's mithilfe des "Input-Knoten" die Interaktionsmöglichkeiten des Nutzers mit einbeziehen. diese Fehlen komplett
4. Skizze und AD's immer in eine Datei packen!
5. Bedingungen im AD immer in eckige Klammern schreiben.
6. Code Ordner im Repository bitte mit Unterordnern wie z.B. `ts` oder `konzept` strukturieren.
7. Event-Listener immer möglichst weit oben im Code platzieren.
8. Variablen die global sind werden auch ganz oben im Code deklariert.
9. Code enthält sehr viel Weißraum, daher sieht es etwas unübersichtlich aus.
10. Der Code funktioniert nicht richtig. Hat man die Karten einmal sortiert, lassen sie sich nichtmehr legen.

_15.04 | 12:09 (mb)_

**Comment by Plagiatus** [comment]
Skizze ist Teil des Konzeptes. Alles in eine Datei, ab dem nächsten Mal gibt es eine Ampel dafür!
Typisieren!
